// Generated by CoffeeScript 1.9.1

/*
This is separate CoffeeScript addon for Clinch processor
 */

(function() {
  var CS_BARE, CoffeeScript, extension, processor;

  CoffeeScript = require('coffee-script');

  CS_BARE = true;

  extension = '.coffee';

  processor = function(data, filename, cb) {
    var content, error;
    try {
      content = CoffeeScript.compile(data, {
        bare: CS_BARE,
        filename: filename
      });
    } catch (_error) {
      error = _error;
      return cb(error);
    }
    return cb(null, content, true);
  };

  module.exports = {
    extension: extension,
    processor: processor
  };

}).call(this);
